// <auto-generated />
using System;
using Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueAPI.WebApi.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200114052416_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Dados.Produto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67fa5aaf-579e-4086-876a-846a5e3264a7"),
                            Nome = "RTX 2060",
                            Quantidade = 50,
                            Valor = 2000.00m
                        },
                        new
                        {
                            Id = new Guid("b7a7294b-9d41-4cf5-b778-73ed6ee12597"),
                            Nome = "RTX 2060 SUPER",
                            Quantidade = 60,
                            Valor = 2500.00m
                        },
                        new
                        {
                            Id = new Guid("9ef9b714-5a63-492b-95a2-2e7fedf350b9"),
                            Nome = "RTX 2070",
                            Quantidade = 10,
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = new Guid("9f823f33-1655-46f8-9858-cf0387292ac3"),
                            Nome = "RTX 2070 SUPER",
                            Quantidade = 8,
                            Valor = 3500.00m
                        },
                        new
                        {
                            Id = new Guid("bb414e49-3ee3-4221-9475-9062f4e95a82"),
                            Nome = "RTX 2080 SUPER",
                            Quantidade = 5,
                            Valor = 4000.00m
                        },
                        new
                        {
                            Id = new Guid("343a7faf-1657-48fd-912e-af42e996e146"),
                            Nome = "RTX 2080",
                            Quantidade = 1,
                            Valor = 6000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
