// <auto-generated />
using System;
using Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueAPI.WebApi.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Dados.Produto", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be1ee539-1f61-45f4-a7bf-97a140a1a29b"),
                            Nome = "RTX 2060",
                            Quantidade = 50,
                            Valor = 2000.00m
                        },
                        new
                        {
                            Id = new Guid("62f24c8d-f823-4aff-86a6-57373cf0028d"),
                            Nome = "RTX 2060 SUPER",
                            Quantidade = 60,
                            Valor = 2500.00m
                        },
                        new
                        {
                            Id = new Guid("57f6ce8a-1e54-4d30-9332-d9c5cbf186ce"),
                            Nome = "RTX 2070",
                            Quantidade = 10,
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = new Guid("7415f8ce-e427-4a87-9a13-9be812ddaf4b"),
                            Nome = "RTX 2070 SUPER",
                            Quantidade = 8,
                            Valor = 3500.00m
                        },
                        new
                        {
                            Id = new Guid("1aad9964-b9e3-4f46-99e2-6ad12fa1779f"),
                            Nome = "RTX 2080 SUPER",
                            Quantidade = 5,
                            Valor = 4000.00m
                        },
                        new
                        {
                            Id = new Guid("dbc4c222-4b5a-4f41-bffe-90cffb20b781"),
                            Nome = "RTX 2080",
                            Quantidade = 1,
                            Valor = 6000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
